#!/usr/bin/env python3
"""Emit 6510 pack LUTs from the IEC wire model used by SJL 8501.

For each data byte, four 2-bit wire samples (LSB-first pairs) appear on
DATA/CLK. On 8501 those sit in port bits 7/6; on type-1 6510 in bits 0/5.
The LUT maps the 6510 masked sample quad to the data byte.
"""
from __future__ import annotations

from pathlib import Path

MASKED = (0, 1, 32, 33)


def nib(masked: int) -> int:
    masked &= 0x21
    return (masked & 1) | ((masked >> 4) & 2)


def byte_pairs_lsb(byte_val: int) -> list[int]:
    bits = [(byte_val >> i) & 1 for i in range(8)]
    return [
        bits[0] | (bits[1] << 1),
        bits[2] | (bits[3] << 1),
        bits[4] | (bits[5] << 1),
        bits[6] | (bits[7] << 1),
    ]


def masked_6510_from_pair(pair: int, base: int) -> int:
    d0, d1 = pair & 1, (pair >> 1) & 1
    return (base | d0 | (d1 << 5)) & 0x21


def build_lut(base: int) -> list[int]:
    lut = [0] * 256
    for byte_val in range(256):
        pairs = byte_pairs_lsb(byte_val)
        masked = [masked_6510_from_pair(p, base) for p in pairs]
        idx = nib(masked[0]) | (nib(masked[1]) << 2) | (nib(masked[2]) << 4) | (nib(masked[3]) << 6)
        if lut[idx] not in (0, byte_val):
            raise SystemExit(f"LUT collision at idx {idx}: {lut[idx]} vs {byte_val}")
        lut[idx] = byte_val
    assert sorted(lut) == list(range(256)), "LUT must be a bijection"
    return lut


def emit_table(name: str, data: list[int]) -> list[str]:
    lines = [f"{name}:"]
    for row in range(16):
        vals = ", ".join(f"${v:02x}" for v in data[row * 16 : (row + 1) * 16])
        lines.append(f"\t!byte {vals}")
    return lines


def emit() -> list[str]:
    nib256 = [nib(i) for i in range(256)]
    xfer256 = build_lut(0x02)
    busin256 = build_lut(0x00)
    lines = ["; Auto-generated by tests/gen_sjl6510_luts.py — do not edit."]
    lines.extend(emit_table("sjl_nib256", nib256))
    lines.append("")
    lines.append("!align 255, 0")
    lines.extend(emit_table("sjl_byte256", xfer256))
    lines.append("")
    lines.append("!align 255, 0")
    lines.extend(emit_table("sjl_busin_byte256", busin256))
    lines.append("")
    return lines


if __name__ == "__main__":
    out = Path(__file__).with_name("gen_sjl6510_luts.asm")
    out.write_text("\n".join(emit()))
    print(f"wrote {out}")
