#!/usr/bin/env python3
"""Emit position-specific 6510 decode LUTs from the SJL IEC wire model.

For each data byte, four 2-bit wire samples (LSB-first pairs) appear on
DATA/CLK. On 8501 those sit in port bits 7/6; on type-1 6510 in bits 0/5.
Each table maps one raw masked sample to its two bits at the final byte
position. The receiver only needs four indexed loads and three ORs.
"""
from __future__ import annotations

from pathlib import Path

MASKED = (0, 1, 32, 33)


def wire_pair(masked: int) -> int:
    masked &= 0x21
    return ((masked >> 5) & 1) | ((masked & 1) << 1)


def byte_pairs_lsb(byte_val: int) -> list[int]:
    bits = [(byte_val >> i) & 1 for i in range(8)]
    return [
        bits[0] | (bits[1] << 1),
        bits[2] | (bits[3] << 1),
        bits[4] | (bits[5] << 1),
        bits[6] | (bits[7] << 1),
    ]


def masked_6510_from_pair(pair: int, base: int) -> int:
    d0, d1 = pair & 1, (pair >> 1) & 1
    # Preserve the 8501 fold order: pair bit 0 is CLK, pair bit 1 is DATA.
    return (base | (d0 << 5) | d1) & 0x21


def position_table(position: int) -> list[int]:
    assert 0 <= position < 4
    return [wire_pair(raw) << (position * 2) for raw in range(256)]


def emit_table(name: str, data: list[int]) -> list[str]:
    lines = [f"{name}:"]
    for row in range(16):
        vals = ", ".join(f"${v:02x}" for v in data[row * 16 : (row + 1) * 16])
        lines.append(f"\t!byte {vals}")
    return lines


def emit() -> list[str]:
    lines = ["; Auto-generated by tests/gen_sjl6510_luts.py - do not edit."]
    for position in range(4):
        if position:
            lines.append("")
        lines.append("!align 255, 0")
        lines.extend(emit_table(f"sjl_pair{position}_256", position_table(position)))
    lines.append("")
    return lines


if __name__ == "__main__":
    out = Path(__file__).with_name("gen_sjl6510_luts.asm")
    out.write_text("\n".join(emit()))
    print(f"wrote {out}")
